---
abstract: 'Show the release history of a single distribution'
author:
  - 'Kent Fredric <kentnl@cpan.org>'
build_requires:
  ExtUtils::MakeMaker: '0'
  File::Spec: '0'
  Test::Fatal: '0'
  Test::More: '0.89'
  Test::RequiresInternet: '0'
  perl: '5.006'
configure_requires:
  ExtUtils::MakeMaker: '0'
  perl: '5.006'
dynamic_config: 0
generated_by: 'Dist::Zilla version 6.008, CPAN::Meta::Converter version 2.150010'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: CPAN-Distribution-ReleaseHistory
provides:
  CPAN::Distribution::ReleaseHistory:
    file: lib/CPAN/Distribution/ReleaseHistory.pm
    version: '0.002004'
  CPAN::Distribution::ReleaseHistory::Release:
    file: lib/CPAN/Distribution/ReleaseHistory/Release.pm
    version: '0.002004'
  CPAN::Distribution::ReleaseHistory::ReleaseIterator:
    file: lib/CPAN/Distribution/ReleaseHistory/ReleaseIterator.pm
    version: '0.002004'
requires:
  CPAN::DistnameInfo: '0'
  Moo: '1.000008'
  Search::Elasticsearch: '0'
  perl: '5.006'
  strict: '0'
  warnings: '0'
resources:
  bugtracker: https://github.com/kentnl/CPAN-Distribution-ReleaseHistory/issues
  homepage: https://github.com/kentnl/CPAN-Distribution-ReleaseHistory
  repository: https://github.com/kentnl/CPAN-Distribution-ReleaseHistory.git
version: '0.002004'
